centos:
 image: CentOS-7-x86_64-GenericCloud.qcow2
 numcpus: 2
 disks:
  - size: 10
 reservedns: true
 nets:
  - name: default
 pool: default
 cmds:
  - echo root:unix1234 | chpasswd

rhel:
 image: rhel-guest-image-7.2-20160302.0.x86_64.qcow2
 numcpus: 2
 rhnregister: true
 nets:
  - default
 pool: default
 disks:
  - size: 10
 cmds:
  - echo root:unix1234 | chpasswd 

debian:
 image: debian-8-openstack-amd64.qcow2
 numcpus: 1
 memory: 1024
 nets:
  - default
 pool: default
 cmds:
  - echo root:unix1234 | chpasswd 

ubuntu:
 image: xenial-server-cloudimg-amd64-disk1.img
 numcpus: 1
 memory: 1024
 nets:
  - default
 pool: default
 cmds:
  - echo root:unix1234 | chpasswd
  
local_ubuntu1804:
  image: bionic-server-cloudimg-amd64.img
  numcpus: 1
  memory: 512
  nets:
  - default
  pool: default
  cmds:
  - echo root:unix1234 | chpasswd 
